module light(
	swt,
	led);

	//---Ports declearation: generated by Robei---
	input [3:0] swt;
	output [3:0] led;

	wire [3:0] swt;
	wire [3:0] led;

	//----Code starts here: integrated by Robei-----
	assign led[0] = ~swt[0];
	assign led[1] = swt[1] & ~swt[2];
	assign led[3] = swt[2] & swt[3];
	assign led[2] = (swt[1] & ~swt[2]) | (swt[2] & swt[3]);
	
endmodule    //light

