module countdown_uart(
	clk,
	rst_n,
	count_enable,
	tx_valid,
	tx);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input count_enable;
	output tx_valid;
	output tx;

	wire clk;
	wire rst_n;
	wire count_enable;
	wire tx_valid;
	wire tx;
	wire uart2_tx_buf_full;
	wire countdown6_count_full;
	wire [7:0] countdown6_count_out;
	assign tx_valid = uart2_tx_buf_full;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	uart uart2(
		.clk(clk),
		.rst_n(rst_n),
		.tx_en(countdown6_count_full),
		.data_send(countdown6_count_out),
		.tx_buf_full(uart2_tx_buf_full),
		.tx(tx));

	countdown countdown6(
		.clk(clk),
		.rst_n(rst_n),
		.count_en(count_enable),
		.count_full(countdown6_count_full),
		.count_out(countdown6_count_out),
		.tx_done(uart2_tx_buf_full));

endmodule    //countdown_uart

