module generate_clk(
	clk,
	rst_n,
	clk_out);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	output clk_out;

	wire clk;
	wire rst_n;
	reg clk_out;

	//----Code starts here: integrated by Robei-----
		`define DEL 1
		
	  //
		// Division is 78, which duty is 50% and frequency is 153846Hz
	  // 153846 = 16 * 9600
		//
	  reg [6:0] cnt;
	
	  always @( posedge clk or negedge rst_n ) begin
	    if( ~rst_n ) begin
	      cnt     <= #`DEL 7'd0;
	      clk_out <= #`DEL 1'b0;
	    end
	    else if( cnt == 7'd38 ) begin
	      cnt     <= #`DEL cnt + 7'd1;
	      clk_out <= #`DEL 1'b1;
	    end
	    else if( cnt == 7'd77 ) begin
	      cnt     <= #`DEL 7'd0;
	      clk_out <= #`DEL 1'b0;
	    end
	    else begin
	      cnt     <= #`DEL cnt + 7'd1;
	    end
	  end  
	
endmodule    //generate_clk

