module tran_data(
	clk,
	rst_n,
	count_en,
	tx_doing,
	tx);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input count_en;
	output tx_doing;
	output tx;

	wire clk;
	wire rst_n;
	wire count_en;
	wire tx_doing;
	wire tx;
	wire generate_clk1_clk_out;

	//----Code starts here: integrated by Robei-----
	wire count_start;
	assign count_start = ~count_en;  // Input enable signal
	
	wire tx_inv;
	assign tx_doing = ~tx_inv;   // Output enable signal
	
	
	
	//---Module instantiation---
	generate_clk generate_clk1(
		.clk(clk),
		.rst_n(rst_n),
		.clk_out(generate_clk1_clk_out));

	countdown_uart countdown_uart3(
		.clk(generate_clk1_clk_out),
		.rst_n(rst_n),
		.count_enable(count_start),
		.tx_valid(tx_inv),
		.tx(tx));

endmodule    //tran_data

