module uart_led(
	clk,
	rst_n,
	rx,
	u_led_valid,
	u_led0,
	u_led1,
	u_led2);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input rx;
	output u_led_valid;
	output [3:0] u_led0;
	output [3:0] u_led1;
	output [3:0] u_led2;

	wire clk;
	wire rst_n;
	wire rx;
	wire u_led_valid;
	wire [3:0] u_led0;
	wire [3:0] u_led1;
	wire [3:0] u_led2;
	wire uart1_rx_buf_full;
	wire [8:0] uart1_data_received;

	//----Code starts here: integrated by Robei-----
	
	
	//---Module instantiation---
	uart uart1(
		.clk(clk),
		.rst_n(rst_n),
		.rx(rx),
		.rx_buf_full(uart1_rx_buf_full),
		.data_received(uart1_data_received));

	led led2(
		.clk(clk),
		.rst_n(rst_n),
		.data_in(uart1_data_received),
		.display_en(uart1_rx_buf_full),
		.led0(u_led0),
		.led1(u_led1),
		.led2(u_led2),
		.led_done(u_led_valid));

endmodule    //uart_led

