module andgate(
	a,
	b,
	y);

	//---Ports declearation: generated by Robei---
	input a;
	input b;
	output y;

	wire a;
	wire b;
	wire y;

	//----Code starts here: integrated by Robei-----
	assign y = a&b;
	
	
	
	
	
endmodule    //andgate

