module alu(
	A,
	B,
	F,
	R,
	D,
	op);

	//---Ports declearation: generated by Robei---
	input [7:0] A;
	input [7:0] B;
	input F;
	output [7:0] R;
	output D;
	input [3:0] op;

	wire [7:0] A;
	wire [7:0] B;
	wire F;
	reg [7:0] R;
	reg D;
	wire [3:0] op;

	//----Code starts here: integrated by Robei-----
	always @ (A or B or op or F)
	begin
		case ( op )
			3'b000: {D,R}=A&B; //实现与运算
			3'b001: {D,R}=A|B; //实现或运算
			3'b010: {D,R}=~A; //实现非运算
			3'b011: {D,R}=A^B; //实现异或运算
			3'b100: {D,R}=A+B; //实现不带进位的加运算
			3'b101: {D,R}=A+B+F; //实现带进位的加运算
			3'b110: {D,R}=A-B; //实现不带借位的减运算
			3'b111: {D,R}=A-B-F; //实现带借位的减运算
			default: {D,R}=A&B; //默认为与运算
		endcase
	end
	
endmodule    //alu

