module alu32(
	A0,
	B0,
	A1,
	B1,
	A2,
	B2,
	A3,
	B3,
	op,
	F,
	R1,
	R2,
	R3,
	R4,
	D);

	//---Ports declearation: generated by Robei---
	input [7:0] A0;
	input [7:0] B0;
	input [7:0] A1;
	input [7:0] B1;
	input [7:0] A2;
	input [7:0] B2;
	input [7:0] A3;
	input [7:0] B3;
	input [3:0] op;
	input F;
	output [7:0] R1;
	output [7:0] R2;
	output [7:0] R3;
	output [7:0] R4;
	output D;

	wire [7:0] A0;
	wire [7:0] B0;
	wire [7:0] A1;
	wire [7:0] B1;
	wire [7:0] A2;
	wire [7:0] B2;
	wire [7:0] A3;
	wire [7:0] B3;
	wire [3:0] op;
	wire F;
	wire [7:0] R1;
	wire [7:0] R2;
	wire [7:0] R3;
	wire [7:0] R4;
	wire D;
	wire alu1_D;
	wire alu2_D;
	wire alu3_D;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	alu alu1(
		.A(A0),
		.B(B0),
		.F(F),
		.R(R1),
		.D(alu1_D),
		.op(op));

	alu alu2(
		.A(A1),
		.B(B1),
		.F(alu1_D),
		.R(R2),
		.D(alu2_D),
		.op(op));

	alu alu3(
		.A(A2),
		.B(B2),
		.F(alu2_D),
		.R(R3),
		.D(alu3_D),
		.op(op));

	alu alu4(
		.A(A3),
		.B(B3),
		.F(alu3_D),
		.R(R4),
		.D(D),
		.op(op));

endmodule    //alu32

