module count_uart_16550(
	clk,
	rst_n,
	count_en,
	tx,
	tx_valid);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input count_en;
	output tx;
	output tx_valid;

	wire clk;
	wire rst_n;
	wire count_en;
	wire tx;
	wire tx_valid;
	wire countdown2_count_full;
	wire [7:0] countdown2_count_out;
	wire uart2_tx_buf_full;
	assign tx_valid = uart2_tx_buf_full;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	countdown countdown2(
		.clk(clk),
		.rst_n(rst_n),
		.count_en(count_en),
		.count_full(countdown2_count_full),
		.count_out(countdown2_count_out),
		.tx_done(uart2_tx_buf_full));

	uart uart2(
		.clk(clk),
		.rst_n(rst_n),
		.tx_en(countdown2_count_full),
		.data_send(countdown2_count_out),
		.parity(3'b010),
		.stop_bit(2'b01),
		.data_bit(4'd8),
		.tx_buf_full(uart2_tx_buf_full),
		.tx(tx));

endmodule    //count_uart_16550

