module tran_data(
	clk,
	rst_n,
	count_enable,
	tx,
	tx_done);

	//---Ports declearation: generated by Robei---
	input clk;
	input rst_n;
	input count_enable;
	output tx;
	output tx_done;

	wire clk;
	wire rst_n;
	wire count_enable;
	wire tx;
	wire tx_done;
	wire generate_clk1_clk_out;

	//----Code starts here: integrated by Robei-----
	/*wire count_start;
	assign count_start = ~count_enable;  // Input enable signal
	*/
	wire tx_inv;
	assign tx_done = ~tx_inv;   // Output enable signal
	
	
	
	//---Module instantiation---
	generate_clk generate_clk1(
		.clk(clk),
		.rst_n(rst_n),
		.baud_rate(19'd9600),
		.clk_out(generate_clk1_clk_out));

	count_uart_16550 count_uart_165502(
		.clk(generate_clk1_clk_out),
		.rst_n(rst_n),
		.count_en(count_enable),
		.tx(tx),
		.tx_valid(tx_inv));

endmodule    //tran_data

